### ISSUE TITLE
demo运行时报错

### ISSUE THREAD

**Issue by NanyuZhang0812** [simple-robot/simbot-mirai-demo#1]
---
[2021-05-26T22:54:48.117862500]-[INFO ] | love.simbot.example.SimbotExampleApplication : Active resources: [simbot.properties, simbot.yml]
Exception in thread "main" java.lang.IllegalAccessError: class love.forte.common.utils.annotation.AnnotationInvocationHandler (in unnamed module @0x1a93a7ca) cannot access class sun.reflect.annotation.ExceptionProxy (in module java.base) because module java.base does not export sun.reflect.annotation to unnamed module @0x1a93a7ca
	at love.forte.common.utils.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:98)
	at jdk.proxy1/jdk.proxy1.$Proxy3.value(Unknown Source)
	at love.forte.common.ioc.DependCenter.inject0(DependCenter.kt:195)
	at love.forte.common.ioc.DependCenter.inject(DependCenter.kt:154)
	at love.forte.common.ioc.DependCenter.register(DependCenter.kt:832)
	at love.forte.simbot.core.SimbotApp.initDependCenterWithAutoConfigures(SimbotApp.kt:229)
	at love.forte.simbot.core.SimbotApp.run$core(SimbotApp.kt:185)
	at love.forte.simbot.core.SimbotApp$Run.run(SimbotApp.kt:416)
	at love.forte.simbot.core.SimbotApp$Run.run$default(SimbotApp.kt:384)
	at love.forte.simbot.core.SimbotApp.run(SimbotApp.kt)
	at love.simbot.example.SimbotExampleApplication.main(SimbotExampleApplication.java:29)
---
在运行demo时出现如上报错，jdk版本是AdoptOpenJDK8_292

**Comment by ForteScarlet** [comment]
module模块化错误应该是java9之后才会引入的特性，这似乎与你说的使用8版本的情况不符，检查下IDE所配置的真正运行的java版本是否真的是8

**Comment by NanyuZhang0812** [comment]
感谢，解决了。我之前把项目sdk设置为jdk8，但似乎还是运行的是另一个。
